VERILOG_SOURCES = $(SRC_DIR)/coil_controller.sv
VERILOG_SOURCES += $(SRC_DIR)/cross_correlation.sv
VERILOG_SOURCES += $(SRC_DIR)/cartesian_to_polar.sv
VERILOG_SOURCES += $(SRC_DIR)/polar_to_cartesian.sv
VERILOG_SOURCES += $(SRC_DIR)/magnitude_phase_estimator.sv
VERILOG_SOURCES += $(SRC_DIR)/pi_controller.sv

TOPLEVEL = coil_controller

include ../Makefile.common
