VERILOG_SOURCES = $(SRC_DIR)/magnitude_phase_estimator.sv
VERILOG_SOURCES += $(SRC_DIR)/cartesian_to_polar.sv
VERILOG_SOURCES += $(SRC_DIR)/cross_correlation.sv
VERILOG_SOURCES += $(SRC_DIR)/cross_correlation_two_signals.sv
VERILOG_SOURCES += $(SRC_DIR)/cross_correlation_two_signals_sparse.sv


TOPLEVEL = magnitude_phase_estimator

include ../Makefile.common
